language: generic
sudo: required
services:
  - docker
# before_install:
#   - docker build -t yusuf/client:v0 -f ./client/Dockerfile.dev ./client
# script:
#   - docker run -e CI=true yusuf/client:v0 npm run test

before_install:
  - docker build -t yusuf/client:v0 ./client
  - docker build -t yusuf/server:v0 ./server
  - docker build -t yusuf/worker:v0 ./worker
  - docker build -t yusuf/nginx:v0 ./nginx
  - echo "$DOCKER_PASSWORD" | docker  login -u "$DOCKER_ID" --password-stdin

  - docker push yusuf/client:v0
  - docker push yusuf/server:v0
  - docker push yusuf/worker:v0
  - docker push yusuf/nginx:v0
